image: python:3.12

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y awscli zip
  - pip install aws-sam-cli

build-sam:
  stage: build
  script:
    - sam build --template-file garmin-simple-stack.json

deploy-sam:
  stage: deploy
  script:
    - source $GARMINSECRETS
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AAWS_DEFAULT_REGION
    - sam deploy --use-json --template-file garmin-simple-stack.json --stack-name garmin-simple-stack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --s3-bucket cupawandeploybucket --s3-prefix common/cloudformation --region ap-south-1 --parameter-overrides ParameterKey=SourceName,ParameterValue=$Source_Name ParameterKey=ApplicationName,ParameterValue=$Application_Name ParameterKey=Env,ParameterValue=$Env ParameterKey=TelegramBotToken,ParameterValue=$TELEGRAM_BOT_TOKEN ParameterKey=TelegramChatIds,ParameterValue=$TELEGRAM_CHAT_IDS ParameterKey=MyGarminPassword,ParameterValue=$MY_GARMIN_PASSWORD ParameterKey=MyEmailAddress,ParameterValue=$MY_EMAIL_ADDRESS ParameterKey=AwsAccessKey,ParameterValue=$AWS_ACCESS_KEY ParameterKey=AwsSecretAccessKey,ParameterValue=$AWS_SECRET_ACCESS_KEY ParameterKey=AwsS3BucketName,ParameterValue=$AWS_S3_BUCKET_NAME ParameterKey=AwsS3LambdaFolderKey,ParameterValue=$AWS_S3LAMBDA_FOLDER_KEY ParameterKey=AwsS3LambdaGarminFilename,ParameterValue=$AWS_S3LAMBDA_GARMIN_FILENAME ParameterKey=MongoDbConnectionString,ParameterValue=$MONGODB_CONNECTION_STRING ParameterKey=MongoDbDatabase,ParameterValue=$MONGODB_DATABASE ParameterKey=BulletinEmailAddress,ParameterValue=$BULLETIN_EMAIL_ADDRESS ParameterKey=BulletinEmailAddressAppPassword,ParameterValue=$BULLETIN_EMAIL_ADDRESS_APP_PASSWORD ParameterKey=RunningMapPath,ParameterValue=$RUNNING_MAP_PATH ParameterKey=GoogleApiKey,ParameterValue=$GOOGLE_API_KEY ParameterKey=GoogleMapsApiPath,ParameterValue=$GOOGLE_MAPS_API_PATH ParameterKey=RecEmail,ParameterValue=$REC_EMAIL


  only:
    - dev






